### ISSUE TITLE
Package registration

### ISSUE THREAD

**Issue by jakubwro** [sairus7/MaxMinFilters.jl#2]
Hi! I benchmarked your package myself and it is incredible fast. I suggest to register it.
According to the discourse discussion I agree that name could be changed and we should consider consolidation with other similar packages. I can spend some time on it, as I need those algorithms for my project.

**Comment by sairus7** [comment]
Thanks, made a PR:
https://github.com/JuliaRegistries/General/pull/8644

**Comment by sairus7** [comment]
PR was merged - closing this issue.
