### ISSUE TITLE
the comparison should be with `RollingFunctions.rollmax` not `runmax`

### ISSUE THREAD

**Issue by JeffreySarnoff** [sairus7/MaxMinFilters.jl#3]
Your routines are quite a bit faster, this correction does not change that fact. Still `runmax` does more work (tapirs the values to process) than does `rollmax`.  `rollmax` is the functional comparison.  This is unlikely to change the graphs for windows < 150.  Nice work!

**Comment by sairus7** [comment]
Thanks! Changed to from `RollingFunctions.runmax` to `RollingFunctions.rollmax` and updated plots. There is indeed no visible result changes.
