### ISSUE TITLE
Dependency on DataStructures.jl?

### ISSUE THREAD

**Issue by bencherian** [sairus7/MaxMinFilters.jl#4]
Is there a reason for the dependency on a specific version of DataStructures.jl? It doesn't appear to actually be used anywhere...

**Comment by sairus7** [comment]
Yes, there is local implementation of ring buffer, so DataStructures is not needed at all.

closed by https://github.com/sairus7/MaxMinFilters.jl/commit/59ffd2dabce38b66ddfd33e6cb1f82b72fb3c3e3
